# Generated by Django 4.1.6 on 2023-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="link/images/"),
        ),
    ]
